name: Build & Push to Docker Hub
on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: git_sha
        run: echo "::set-output name=git_sha::$(git rev-parse --short HEAD)"
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          build-args: |
            GIT_SHA=${{ steps.git_sha.outputs.git_sha }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ericboehs/rpi-locator-checker:latest
